apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-dev
  namespace: experimental-pipeline
spec:
  resources:
  - name: resource-for-pipeline
    type: git
  tasks:
  - name: dev-prep
    resources:
      inputs:
      - name: pipeline-app-image
        resource: resource-for-pipeline
    taskRef:
      name: prepare-dev-1
  - name: dev-apply
    resources:
      inputs:
      - name: pipeline-app-image
        resource: resource-for-pipeline
    runAfter:
    - dev-prep
    taskRef:
      name: apply-dev-1
  - name: post-dev-check
    runAfter:
    - dev-apply
    taskRef:
      name: post-dev-sanity-1
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-dev
  namespace: experimental-pipeline
spec:
  pipelineRef:
    name: pipeline-dev
  resources:
  - name: resource-for-pipeline
    resourceRef:
      name: pipeline-app-resource
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pipeline-app-resource
  namespace: experimental-pipeline
spec:
  params:
  - name: url
    value: https://github.com/yuwenma/app-pipeline-demo.git
  type: git
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-dev-1
  namespace: experimental-pipeline
spec:
  inputs:
    resources:
    - name: pipeline-app-image
      type: git
  steps:
  - args:
    - -c
    - appctl init pipeline-app --app-config-repo github.com/yuwenma/app-pipeline-demo
      && cd /workspace/pipeline-app && gcloud config list && appctl apply dev && kubectl
      get releasetrack -n pipeline-app-dev
    command:
    - /bin/bash
    image: gcr.io/yuwenma-gke-playground/appctl:v11.0.0-quickstart
    name: apply
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: post-dev-sanity-1
  namespace: experimental-pipeline
spec:
  steps:
  - args:
    - -c
    - echo "Staging release Succeed!!!"
    command:
    - /bin/bash
    image: gcr.io/yuwenma-gke-playground/appctl:v11.0.0-quickstart
    name: check
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: prepare-dev-1
  namespace: experimental-pipeline
spec:
  inputs:
    resources:
    - name: pipeline-app-image
      type: git
  steps:
  - args:
    - -c
    - appctl init pipeline-app --app-config-repo github.com/yuwenma/app-pipeline-demo
      && cd /workspace/pipeline-app && appctl prepare dev
    command:
    - /bin/bash
    image: gcr.io/yuwenma-gke-playground/appctl:v11.0.0-quickstart
    name: prepare
